## If you want to use fancybox please set the value to true
fancybox: false

## Your Disqus ID
# disqus: abandonzhang

## Your DuoShuo ID
duoshuo: abandonzhang

# 菜单栏
menu:
  - page: home
    directory: .
  - page: tags
    directory: tags/
  - page: about
    directory: about/
  - page: readings
    directory: readings/
  - page: rss
    directory: atom.xml
